package data

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateTableKeys emits a compact Go constant block for table field names.
// It helps projects avoid manual string literals in query/update code.
func GenerateTableKeys(tableName string, table Table) string {
	tableName = strings.TrimSpace(tableName)
	if tableName == "" {
		tableName = strings.TrimSpace(table.Name)
	}
	if tableName == "" {
		tableName = "table"
	}
	keys := make([]string, 0, len(table.Fields))
	for key := range table.Fields {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	typeName := toExported(tableName) + "Field"
	lines := []string{
		"// Code generated by data.GenerateTableKeys. DO NOT EDIT.",
		"package datafields",
		"",
		fmt.Sprintf("type %s string", typeName),
		"",
		"const (",
	}
	for _, key := range keys {
		lines = append(lines, fmt.Sprintf("\t%s%s %s = %q", toExported(tableName), toExported(key), typeName, key))
	}
	lines = append(lines, ")")
	return strings.Join(lines, "\n")
}

func toExported(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "X"
	}
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return !(r >= '0' && r <= '9') && !(r >= 'a' && r <= 'z') && !(r >= 'A' && r <= 'Z')
	})
	if len(parts) == 0 {
		return "X"
	}
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	out := strings.Join(parts, "")
	if out == "" {
		return "X"
	}
	return out
}
